// ─── Core domain types shared across the client store, API and UI ───────────

export type ID = string;

export type ThemeMode = "light" | "dark" | "system";

export type UserRole = "student" | "teacher" | "admin";

export interface UserProfile {
  id: ID;
  name: string;
  email: string;
  avatar: string; // emoji avatar
  role: UserRole;
  joinedAt: number;
  settings: UserSettings;
}

export interface UserSettings {
  theme: ThemeMode;
  dailyReviewTarget: number; // cards per day
  dailyStudyMinutesTarget: number;
  desiredRetention: number; // FSRS requested retention, e.g. 0.9
  notifications: {
    reviewReminders: boolean;
    examReminders: boolean;
    achievementAlerts: boolean;
    motivational: boolean;
  };
  reducedMotion: boolean;
}

// ─── Courses / subjects ──────────────────────────────────────────────────────

export interface Subject {
  id: ID;
  name: string;
  emoji: string;
  color: string; // one of the palette keys
  examDate?: number;
  goal?: string;
  pinned: boolean;
  archived: boolean;
  createdAt: number;
}

// ─── Notes ───────────────────────────────────────────────────────────────────

export interface Note {
  id: ID;
  subjectId: ID | null;
  title: string;
  /** Markdown source. Rendered with the built-in markdown renderer. */
  content: string;
  tags: string[];
  pinned: boolean;
  createdAt: number;
  updatedAt: number;
  /** Lightweight version history: last N snapshots. */
  versions: { savedAt: number; content: string }[];
}

// ─── Flashcards & spaced repetition ─────────────────────────────────────────

export type CardKind = "basic" | "cloze" | "mcq" | "truefalse";

/** FSRS card learning state. */
export type CardState = "new" | "learning" | "review" | "relearning";

export type Rating = 1 | 2 | 3 | 4; // Again / Hard / Good / Easy

export interface FsrsState {
  state: CardState;
  /** Epoch ms when the card is due. */
  due: number;
  /** Memory stability in days (FSRS). */
  stability: number;
  /** Difficulty 1..10 (FSRS). */
  difficulty: number;
  /** Which learning/relearning step the card is on. */
  step: number;
  reps: number;
  lapses: number;
  lastReview: number | null;
}

export interface Flashcard {
  id: ID;
  deckId: ID;
  kind: CardKind;
  /** Question / cloze text (use {{c1::answer}} syntax for cloze). */
  front: string;
  back: string;
  /** For MCQ cards. */
  options?: string[];
  answerIndex?: number;
  tags: string[];
  createdAt: number;
  srs: FsrsState;
  history: { at: number; rating: Rating; elapsedDays: number }[];
}

export interface Deck {
  id: ID;
  subjectId: ID | null;
  name: string;
  description: string;
  emoji: string;
  createdAt: number;
}

// ─── Quizzes & exams ─────────────────────────────────────────────────────────

export type QuestionKind = "mcq" | "truefalse" | "short" | "fill";

export interface QuizQuestion {
  id: ID;
  kind: QuestionKind;
  prompt: string;
  options?: string[]; // mcq
  answerIndex?: number; // mcq / truefalse (0 = true, 1 = false)
  answerText?: string; // short / fill
  explanation: string;
  topic?: string;
}

export interface Quiz {
  id: ID;
  subjectId: ID | null;
  title: string;
  description: string;
  questions: QuizQuestion[];
  /** Exam mode adds timing + no instant feedback. */
  timeLimitMinutes?: number;
  createdAt: number;
  source: "manual" | "ai" | "seed";
}

export interface QuizAttempt {
  id: ID;
  quizId: ID;
  startedAt: number;
  finishedAt: number;
  mode: "practice" | "exam" | "oral";
  answers: { questionId: ID; given: string; correct: boolean }[];
  scorePercent: number;
}

// ─── Planner ─────────────────────────────────────────────────────────────────

export type PlanKind = "study" | "review" | "quiz" | "break" | "exam";

export interface PlannerTask {
  id: ID;
  /** ISO date (yyyy-mm-dd) the task is scheduled for. */
  date: string;
  title: string;
  subjectId: ID | null;
  kind: PlanKind;
  durationMin: number;
  done: boolean;
  auto: boolean; // generated by the AI planner
}

// ─── AI tutor ────────────────────────────────────────────────────────────────

export interface ChatMessage {
  id: ID;
  role: "user" | "assistant";
  content: string;
  at: number;
}

export interface TutorThread {
  id: ID;
  title: string;
  subjectId: ID | null;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
}

// ─── Gamification & analytics ────────────────────────────────────────────────

export interface DayActivity {
  /** ISO date (yyyy-mm-dd). */
  date: string;
  xp: number;
  reviews: number;
  reviewsCorrect: number;
  quizQuestions: number;
  quizCorrect: number;
  studyMinutes: number;
  notesEdited: number;
}

export interface Gamification {
  xp: number;
  coins: number;
  streak: { current: number; best: number; lastActiveDay: string | null };
  /** achievement id → epoch ms unlocked */
  unlocked: Record<string, number>;
}

// ─── Root state ──────────────────────────────────────────────────────────────

export interface AppState {
  version: number;
  onboarded: boolean;
  profile: UserProfile;
  game: Gamification;
  subjects: Subject[];
  notes: Note[];
  decks: Deck[];
  cards: Flashcard[];
  quizzes: Quiz[];
  attempts: QuizAttempt[];
  planner: PlannerTask[];
  threads: TutorThread[];
  activity: DayActivity[];
}
